ALTER TABLE answer DISABLE TRIGGER ALL;
ALTER TABLE groups DISABLE TRIGGER ALL;
ALTER TABLE member DISABLE TRIGGER ALL;
ALTER TABLE question DISABLE TRIGGER ALL;
ALTER TABLE recommend_question DISABLE TRIGGER ALL;
ALTER TABLE student DISABLE TRIGGER ALL;
ALTER TABLE student_teacher DISABLE TRIGGER ALL;
ALTER TABLE teacher DISABLE TRIGGER ALL;

TRUNCATE TABLE answer CASCADE;
TRUNCATE TABLE groups CASCADE;
TRUNCATE TABLE member CASCADE;
TRUNCATE TABLE question CASCADE;
TRUNCATE TABLE recommend_question CASCADE;
TRUNCATE TABLE student CASCADE;
TRUNCATE TABLE student_teacher CASCADE;
TRUNCATE TABLE teacher CASCADE;

ALTER TABLE answer ENABLE TRIGGER ALL;
ALTER TABLE groups ENABLE TRIGGER ALL;
ALTER TABLE member ENABLE TRIGGER ALL;
ALTER TABLE question ENABLE TRIGGER ALL;
ALTER TABLE recommend_question ENABLE TRIGGER ALL;
ALTER TABLE student ENABLE TRIGGER ALL;
ALTER TABLE student_teacher ENABLE TRIGGER ALL;
ALTER TABLE teacher ENABLE TRIGGER ALL;
